### ISSUE TITLE
Caused by android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by vinodkumarsagitla** [DevCycleHQ/android-client-sdk#132]
I am unable to find this crash at my end but this crash show on Firebase Crashlytics with below exception:
Caused by android.os.NetworkOnMainThreadException:
       at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1667)
       at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:431)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:666)
       at com.android.org.conscrypt.ConscryptEngineSocket$SSLOutputStream.-$$Nest$mwriteInternal(ConscryptEngineSocket.java)
       at com.android.org.conscrypt.ConscryptEngineSocket.drainOutgoingQueue(ConscryptEngineSocket.java:594)
       at com.android.org.conscrypt.ConscryptEngineSocket.close(ConscryptEngineSocket.java:489)
       at okhttp3.internal._UtilJvmKt.closeQuietly(-UtilJvm.kt:229)
       at okhttp3.internal.connection.RealConnectionPool.evictAll(RealConnectionPool.kt:155)
       at okhttp3.ConnectionPool.evictAll(ConnectionPool.kt:57)
       at com.devcycle.sdk.android.eventsource.EventSource.close(EventSource.java:229)
       at com.devcycle.sdk.android.api.DVCClient$onResumeApplication$1.invoke(DVCClient.kt:112)
       at com.devcycle.sdk.android.api.DVCClient$onResumeApplication$1.invoke(DVCClient.kt:110)
       at com.devcycle.sdk.android.api.DVCLifecycleCallbacks.onActivityResumed(DVCLifecycleCallbacks.kt:31)
       at android.app.Application.dispatchActivityResumed(Application.java:450)
       at android.app.Activity.dispatchActivityResumed(Activity.java:1482)
       at android.app.Activity.onResume(Activity.java:2043)
       at androidx.fragment.app.FragmentActivity.onResume(FragmentActivity.java:310)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1531)
       at android.app.Activity.performResume(Activity.java:8734)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:5351)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:5444)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:225)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by ajwootto** [comment]
hey @vinodkumarsagitla, thanks for the report. Just letting you know we're looking at this internally and will keep you updated on a potential fix

**Comment by jsalaber** [comment]
@vinodkumarsagitla This should be fixed in `1.4.1`.
