### ISSUE TITLE
DevCycle SDK Failed to Initialize!

### ISSUE THREAD

**Issue by vinodkumarsagitla** [DevCycleHQ/android-client-sdk#64]
Getting below error on when dvcClient is onInitialized 

DevCycle SDK Failed to Initialize!
    com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "variableVariationMap" (class com.devcycle.sdk.android.model.BucketedUserConfig), not marked as ignorable (6 known properties: "environment", "variables", "project", "features", "featureVariationMap", "knownVariableKeys"])
        at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 683] (through reference chain: com.devcycle.sdk.android.model.BucketedUserConfig["variableVariationMap"])
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1650)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:459)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2051)
        at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1459)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:33)
        at retrofit2.converter.jackson.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:23)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)

**Comment by kaushalkapasi** [comment]
Hi @vinodkumarsagitla, thanks for raising this to our attention.

Could you please provide some more information, such as the SDK version and Android version you are seeing this issue on?

We have just deployed a fix and that should solve the issue. We will investigate this further and may release a new version of an SDK as we add new functionality!

Thanks again.

**Comment by kaushalkapasi** [comment]
Hi @vinodkumarsagitla, we've published a new version (`1.0.8`) of the DevCycle Android Client SDK that should also resolve this issue going forward. Going to close this issue now.

https://central.sonatype.dev/artifact/com.devcycle/android-client-sdk/1.0.8/versions
